
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Roboto } from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs";
import {CartProvider} from "./_context/CartContext";

const roboto =  Roboto({ subsets: ['latin'], weight:"700" });


export const metadata = {
  title: {
    template: '%s | Squid',
    default: 'Squid',
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <CartProvider>
    <html lang="en">
      <body
        className={`${roboto.className}  antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
    </CartProvider>
    </ClerkProvider>
  );
}
